# Run via
# FORGE_TOKEN=$(pass tokens/github/OverkillGuy\^forge@api.github.com) poetry run mass-driver run commit_PR.toml --repo-path "git@github.com:OverkillGuy/sphinx-needs-test.git"

[mass-driver.migration]
# Common name to remember the change by across all repos
migration_name = "Bump counter.txt to 2"
commit_message = """Bump counter to 2

Demonstrate mass-driver[1] features by first committing a change locally, then
sending it as PR, in a single CLI run.


[1]: https://jiby.tech/mass-driver

"""

# PatchDriver class to use.
# Selected via plugin name, from "massdriver.drivers" entrypoint
driver_name = "counter"

# The dict will be loaded verbatim into the relevant PatchDriver
driver_config = { counter_file = "counter.txt", target_count = 2}

[mass-driver.forge]
forge_name = "github"

base_branch = "main"
# Branch name for migrations defaults to used PatchDriver's plugin name
head_branch = "counter"
draft_pr = true
pr_title = "Bump counter to 2"
pr_body = """Demonstrate mass-driver[1] features by first committing a change locally, then
sending it as PR, in a single CLI run.

[1]: https://jiby.tech/mass-driver
"""
# We really need to push first.
git_push_first = true
