[project]
name = "mass-driver-plugins"
version = "0.18.0-a1"
requires-python = ">=3.11"
dependencies = [
    "pygithub == 2.1.1",
    "mass-driver-core",
]

# For this dep, look in the workspaces to the side of this package
[tool.uv.sources]
mass-driver-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.plugins.'massdriver.drivers']
counter = 'mass_driver_plugins.drivers.counter:Counter'
precommit = 'mass_driver_plugins.drivers.precommit:PrecommitAutoupdate'
shell = 'mass_driver_plugins.drivers.shell:ShellDriver'
stamper = 'mass_driver_plugins.drivers.stamper:Stamper'

[project.plugins.'massdriver.forges']
dummy = 'mass_driver_plugins.forges.dummy:DummyForge'
github = 'mass_driver_plugins.forges.github:GithubPersonalForge'
github-app = 'mass_driver_plugins.forges.github:GithubAppForge'

[project.plugins.'massdriver.sources']
repo-list = 'mass_driver_plugins.sources.simple:RepolistSource'
repo-filelist = 'mass_driver_plugins.sources.simple:RepoFilelistSource'
template-filelist = 'mass_driver_plugins.sources.simple:TemplateFileSource'
csv-filelist = 'mass_driver_plugins.sources.simple:CSVFileSource'
github-search = 'mass_driver_plugins.sources.github_source:GithubPersonalSource'
github-app-search = 'mass_driver_plugins.sources.github_source:GithubAppSource'

[project.plugins.'massdriver.scanners']
root-files = 'mass_driver_plugins.scanners.basic_scanners:rootlevel_files'
dockerfile-from = 'mass_driver_plugins.scanners.basic_scanners:dockerfile_from_scanner'
